datasource:
  #支持sqlite和mysql
  type: sqlite
  #以下参数都仅在使用mysql数据库时需填写
  #数据库库名
  url: 数据库名
  #数据库用户名
  user: 数据库用户
  #数据库密码
  password: 数据库密码
language:
  inventory:
    LoginTitle: "请登录"
    RegisterTitle: "请注册"
    ReRegisterTitle: "请重新输入密码"
  message:
    wrongPassword: "密码错误！"
    rightPassword: "登陆成功！"
    tooLongPassword: "密码过长！"
    clickFrame: "请不要点击边框！"
    exitInventory: "请不要尝试退出登录/注册页面"
    exitServer: "感谢游玩！"
    twoPasswordNotEquals: "两次输入的密码不一致，请重试！"
    successfulRegister: "注册成功！"
    datasourceWrong: "您的数据库配置有误，报错已发向后台！"
    reloadSuccessful: "插件重载成功！"
    permissionsMissing: "你没有权限使用此指令！"
    wrongArguments: "错误的参数！"
  item:
    frame: "边框"
    capsLock: "大小写锁定"
    quitServer: "退出服务器"
    done: "确认"
    clearInput: "清空输入框"
